#ifndef __NEXTSILICON_SCR7_CONFIG_H
#define __NEXTSILICON_SCR7_CONFIG_H

// #define CFG_SYS_INIT_RAM_ADDR (0xC00000)
// #define CFG_SYS_INIT_RAM_SIZE (0x200000)
                               
#define CFG_SYS_INIT_RAM_SIZE (0x500000)
#define CFG_SYS_INIT_RAM_ADDR (0xB00000)

// #define CFG_SYS_SDRAM_BASE (CONFIG_SYS_LOAD_ADDR)
// #define CFG_SYS_SDRAM_SIZE     (0x80000)

#endif /* __NEXTSILICON_SCR7_CONFIG_H */